### ISSUE TITLE
label style is not changing

### ISSUE THREAD

**Issue by subuhinaseer** [Cnilton/react-native-floating-label-input#1]
![color](https://user-images.githubusercontent.com/63515806/79052460-2482c800-7c50-11ea-984a-5292f97c7f87.PNG)

**Comment by Cnilton** [comment]
Sorry, it's working as expected. It was only my mistake not to show instructions for the label styles. Will update props and README.md

**Comment by Cnilton** [comment]
Thank you for your cooperation. I'll close this for now, since it was just a prop documentation flaw.

**Comment by subuhinaseer** [comment]
Thanks for you response.. but it's still not working don't know why?
Am i doing it correctly?
![color1](https://user-images.githubusercontent.com/63515806/79061590-29c13080-7cab-11ea-897d-217faa220f3e.PNG)

**Comment by Cnilton** [comment]
I think you didn't update your version. These changes were just implemented in version 1.0.6. Can you verify that you're using the most recent version?

![Screenshot_2020-04-12-10-36-44-1 1](https://user-images.githubusercontent.com/40298250/79070148-2bd6bf80-7caa-11ea-8668-79b83f2e7e6e.png)
![20200412_104501 1](https://user-images.githubusercontent.com/40298250/79070222-ba4b4100-7caa-11ea-90a7-92e21be74649.jpg)

**Comment by subuhinaseer** [comment]
i have updated the version...
![pkg](https://user-images.githubusercontent.com/63515806/79093621-43777c00-7d6e-11ea-84f8-53a42bf329e1.PNG)

**Comment by Cnilton** [comment]
I see... Can you please show all your styles?

**Comment by subuhinaseer** [comment]
this is complete code of FloatingLabel component
![11](https://user-images.githubusercontent.com/63515806/79120990-b05e3680-7dad-11ea-8f17-2af714d529af.PNG)
![21](https://user-images.githubusercontent.com/63515806/79120998-b18f6380-7dad-11ea-8250-fa2775d11225.PNG)



import React from 'react'
import { View, StyleSheet } from 'react-native'
import FloatingLabelInput from 'react-native-floating-label-input';
const Floatinglabel = ({ label, value, changeText, bool, yourfunction }) => {
  return (
    <View >
      <FloatingLabelInput
        customLabelStyles={style.title}
        containerStyles={style.TextInput}
        inputStyles={style.innerText}
        showPasswordContainerStyles={style.imgContainer}
        label={label}
        value={value}
        onChange={changeText}
        isPassword={bool}
        onSubmit={() => yourfunction()}
      />
    </View>
  )
}
export default Floatinglabel
const style = StyleSheet.create({
  TextInput: {
    marginTop: 10,
    borderWidth: 0,
    borderRadius: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#b0ac94',
  },
  title: {
    fontSizeFocused: 20,
    fontSizeBlurred: 25,
    colorFocused: '#fcba03',
    colorBlurred: '#000000',
  },
  innerText: {
    color: '#000000',
    fontSize: 20
  },
  imgContainer: {
    backgroundColor: '#ab9f9f',
    borderRadius: 10
  }
})

**Comment by subuhinaseer** [comment]
All styles are working perfectly except the label..

**Comment by Cnilton** [comment]
So, I couldn't reproduce the issue as you can see in the photos... Can you please, delete your node_modules folder and install the modules again (yarn or npm install)?

![Screenshot_2020-04-13-10-27-03-1 1](https://user-images.githubusercontent.com/40298250/79123971-b7ffea00-7d71-11ea-8cdd-f92e0cf7b760.png)
![20200413_102750 1](https://user-images.githubusercontent.com/40298250/79123992-c221e880-7d71-11ea-9a8a-7231813e306a.jpg)

**Comment by Cnilton** [comment]
> So, I couldn't reproduce the issue as you can see in the photos... Can you please, delete your node_modules folder and install the modules again (yarn or npm install)?
> 
> ![Screenshot_2020-04-13-10-27-03-1 1](https://user-images.githubusercontent.com/40298250/79123971-b7ffea00-7d71-11ea-8cdd-f92e0cf7b760.png)
> ![20200413_102750 1](https://user-images.githubusercontent.com/40298250/79123992-c221e880-7d71-11ea-9a8a-7231813e306a.jpg)

@subuhinaseer, any updates?
