### ISSUE TITLE
Multiline prop doesn't work as expected

### ISSUE THREAD

**Issue by Latropos** [Cnilton/react-native-floating-label-input#104]
Hi,
I was trying to create multiline input field, like the second in the video:

https://user-images.githubusercontent.com/56199675/143885909-4ed1c251-2991-4299-af12-3c43f227b746.mov

To achieve that I had to patch the lib, cause containerStyle is [always partially overwritten](https://github.com/Cnilton/react-native-floating-label-input/blob/49b397ed65d20431c2e4fbc9d244b9157a4a5e49/src/index.tsx#L545-L551) to center the text, without patching only the first result is possible.

I suggest we add a "multiline" functionality to this library
- some new prop must be passed so we can calculate much the multiline component is higher than other stylised components
- This `extraHeight` could be evaluated basing on number of lines or on size in ppt.
- `topBlurred` is   an *Absolute distance from center of the input when blurred*, so it should equal `defaultValue + extraHeight/2`
- `inputStyle` this component should have height set to `defaultValue + extraHeight` and be aligned to top

**Comment by erheron** [comment]
CC @Cnilton @erheron

**Comment by Cnilton** [comment]
@Latropos, @erheron I'll work on it this weekend!

**Comment by AndreiBehel** [comment]
Hi, any progress on multiline functionality?

**Comment by Cnilton** [comment]
Hi @AndreiBehel @erheron and @Latropos this can be accomplished simply by adding **textAlignVertical: 'top'** on `inputStyles` property.

**Comment by OwaisNizami** [comment]
textAlignVertical: 'top' in input styles doesn't work. Need to move the position of the LABEL, not the input. Please guide @Cnilton

**Comment by Cnilton** [comment]
@OwaisNizami I'm sorry, I didn't understand. To achieve that you could use **customLabelStyles** property **topFocused** and **topBlurred**, and to have the input value at the top, you could use the textAlignVertical as I said before.
