### ISSUE TITLE
Remove Spread Operator For Styles to Support Web Better

### ISSUE THREAD

**Issue by Gamma169** [Cnilton/react-native-floating-label-input#105]
Thanks to @santiagofm for finding this.

Looks like the spread operator is not really supported by react-native stylesheets.
https://github.com/necolas/react-native-web/issues/1259#issuecomment-467668100

The linked issue above is in reference to `Stylesheet.create`, but it looks like it applies to how styles are done in this repo as well.
https://github.com/Cnilton/react-native-floating-label-input/blob/2b96c32c9842380a3db88e1766c74b02f7bc5330/src/index.tsx#L535
(edited to use pinned commit line)

You can easily see the difference in unstyled component in android version
![image](https://user-images.githubusercontent.com/6249770/145928335-f9e208c7-0fb9-474a-ae04-d68fbd2bf50b.png)

And web version.
![image](https://user-images.githubusercontent.com/6249770/145928395-6dce2717-c6fd-44a4-889e-37597d5dafba.png)

Solution would be to use array notation for the base styles in this package in order to combine styles.  Might look into it when I have the time.

**Comment by Cnilton** [comment]
Hi @Gamma169, sorry for taking so long. Could you please try the latest version?

**Comment by Gamma169** [comment]
Hi @Cnilton , sorry for not getting back to you too quickly.  I just tried the latest version, and it definitely looks better, but is still not perfect.  Any way you could link the PR/commit that you did to try to fix this issue on your end?  I am having difficulty in finding it.

In the mean time, my team used patch-package to resolve things on our end.  I am attaching the patch-file here so you can see the overall changes that we made.  You can see that anywhere the spread operator was used like this line, we flattened it, and it worked.  Was a simple fix.
https://github.com/Cnilton/react-native-floating-label-input/blob/be199b39698e65b607143c183f0dbfd692b7f5ac/src/index.tsx#L549
(pinned to the latest commit as of this comment)

Although, I believe a better solution is something like this instead of using the `Stylesheet.Flatten`
```j
[react-native-floating-label-input+1.3.11.txt](https://github.com/Cnilton/react-native-floating-label-input/files/8419169/react-native-floating-label-input%2B1.3.11.txt)
s
  containerStyles = [
    containerStyles,
    {
      alignItems: 'center',
      flexDirection: 'row',
      flex: 1,
      zIndex: style?.zIndex !== undefined ? style.zIndex - 6 : 0,
    }
];
```

**Comment by Cnilton** [comment]
Hi @Gamma169, I'm sorry for the hold up on my side either. I'll reopen this, but could you please create a pull request for fixing this?

**Comment by Gamma169** [comment]
Thanks for reopening.  Will try to get to it before month end.

**Comment by Gamma169** [comment]
Hi @Cnilton. A little late, but I found some time today to make updates and check against my code.  Opened a PR if you would like to take a look.  Thanks!
