### ISSUE TITLE
 Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'u.installCoreFunctions')

### ISSUE THREAD

**Issue by prasanna-panneerselvam** [Cnilton/react-native-floating-label-input#107]
iOS app getting crashed when call the react-native-floating-label-input package. 

Xcode version 13
RN version 0.64.2
Reanimated version 2.3.1

<img width="1147" alt="Screenshot 2022-01-17 at 4 36 23 PM" src="https://user-images.githubusercontent.com/11269370/149759641-16599952-d6f3-40eb-9aa9-c207e5e737f9.png">

**Comment by Cnilton** [comment]
Hi @prasanna-panneerselvam, did you follow reanimated installation steps?
