### ISSUE TITLE
Support suppressHighlighting for Label

### ISSUE THREAD

**Issue by mydesweb** [Cnilton/react-native-floating-label-input#108]
Personally I don't like the visual change that is made when text Label is pressed down. Please allow the `suppressHighlighting={true}` prop to be configured.

**Comment by Cnilton** [comment]
Hi @mydesweb, I'll be adding this feature at the next version, from within **labelProps** property passing parameters as an object.

**Comment by Cnilton** [comment]
@mydesweb there is a new version where you can set props to the label, can you please test it?
