### ISSUE TITLE
We can't change the font-family

### ISSUE THREAD

**Issue by NayaraGoulart** [Cnilton/react-native-floating-label-input#109]
I was using the component in a project, but I can't set fontFamily to labelStyle and inputStyle. It doesn't give an error, but it doesn't apply the style either.

**Comment by Cnilton** [comment]
Hi @NayaraGoulart, were you able to set the font to another component?

**Comment by Cnilton** [comment]
@NayaraGoulart, any updates?

**Comment by NayaraGoulart** [comment]
@Cnilton 
Sorry for the delay!
So, the standard input component I can modify the font-family when in the XML I also put "styles={{ fontWeight: 'normal' }}".
It looks like this:
![image](https://user-images.githubusercontent.com/66383949/159070027-bbbe3751-c29a-4534-be63-66efe868769f.png)
![image](https://user-images.githubusercontent.com/66383949/159070065-6a470b9c-6e73-46ce-9e04-0939007234ad.png)
![image](https://user-images.githubusercontent.com/66383949/159070168-3fcb0d3e-4e0b-40ec-a2f7-a9643881a574.png)

**Comment by Cnilton** [comment]
@NayaraGoulart I could set fonts without any trouble on my side, did you create a configuration file at project root, named `react-native.config.js` for setting the fonts config?

Example:
![image](https://user-images.githubusercontent.com/40298250/159137565-75901f0b-8044-4b56-9061-c65d36275056.png)

react-native.config.js file:
```
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./assets/fonts/'],
};

```

**Comment by NayaraGoulart** [comment]
I did this configurations:

react-native.config.js:
![image](https://user-images.githubusercontent.com/66383949/159246717-d1e0cb50-ce7f-4047-8426-378113281a13.png)

index.js:
![image](https://user-images.githubusercontent.com/66383949/159246876-853d4b81-61d9-43eb-8dd8-5ed5f6927d7f.png)

I've tried to put it globally so I don't have to adjust on each component. I also remember trying on one in particular and it didn't work. When I get back to this project again, I'll try one more time the way you did it, without using a variable.

**Comment by Cnilton** [comment]
@NayaraGoulart I think I see the problem now, you are setting font-family and color to customLabelStyles instead of labelStyles, could you please try it?

**Comment by Cnilton** [comment]
@NayaraGoulart, any updates using labelStyles within the customLabelStyles?

**Comment by NayaraGoulart** [comment]
For sure!
Thank you very much!
It worked globally! I can't believe :)

![image](https://user-images.githubusercontent.com/66383949/159675328-1096a5fa-1bf0-4c10-9ce1-3ab2fc482b0e.png)

**Comment by Cnilton** [comment]
You're welcome @NayaraGoulart, thanks for contributing! I'll mark this issue as `question` and close this now. Feel free to open another issue if there is any other doubt or error.

**Comment by gustavogialim** [comment]
Hey folks, is it possible to set a different `fontFamily ` for the focused label?
