### ISSUE TITLE
Enhancement - Enable multiline to create autosize textarea

### ISSUE THREAD

**Issue by psenechal** [Cnilton/react-native-floating-label-input#11]
While I was looking through your code, I realized how incredibly easy it would be to make a small alteration to enable your library to also become an autosizing Textarea control.

I added a new attribute to Props interface in index.tsx at line 71
```
  isMultiline?: true | false | undefined;
```
and then applied that attribute to the TextInput at line 318
```
        multiline={props.multiline}
```

instant autosizing textarea using floating label and I don't have to roll my own. I even added a nifty "### characters left" on mine.

Just thought I would throw that out there in case you were interested in expanding the libraries functionality. I can create pull request with the changes if you like. Thanks =)

**Comment by Cnilton** [comment]
Hi @psenechal, you are most welcome to create a pull request with the said changes, it would be great to expand this library even more!

**Comment by psenechal** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-09-29 at 10 21 10](https://user-images.githubusercontent.com/1395106/94591924-94582f80-023d-11eb-8be6-97d4a1de71a4.png)

**Comment by psenechal** [comment]
I'll create 2 pull requests. One for just enabling the multiline capability and another for the counter functionality

**Comment by Cnilton** [comment]
Ok, I'll comment about them at their pull requests.

**Comment by Cnilton** [comment]
Can you please update the README.md with an example of the new multiline feature, just as it was done with the mask feature?

**Comment by Cnilton** [comment]
I'm sorry I merge the pull request before thinking of the example

**Comment by Cnilton** [comment]
I'll add the example in README.md and generate a new version to npm, so I'm closing this issue. Thanks for your contribution!
