### ISSUE TITLE
react-native-web

### ISSUE THREAD

**Issue by assafco** [Cnilton/react-native-floating-label-input#112]
Is the floating label supported by react-native-web?
By running in browser I get this error:

TypeError: Cannot read properties of undefined (reading 'style')
Module.<anonymous>
node_modules/react-native-floating-labels/index.js:22
  19 | var textInputPropTypes = TextInput.propTypes || textPropTypes
  20 | var propTypes = {
  21 |   ...textInputPropTypes,
> 22 |   inputStyle: textInputPropTypes.style,
  23 |   labelStyle: textPropTypes.style,
  24 |   disabled: PropTypes.bool,
  25 |   style: ViewPropTypes.style,

**Comment by Cnilton** [comment]
Hi @assafco, I'm sorry, but this lib is supported only by react-native. Maybe in the future, this will be available for web development.
