### ISSUE TITLE
after some time its giving error

### ISSUE THREAD

**Issue by isthisshivam** [Cnilton/react-native-floating-label-input#114]
![image](https://user-images.githubusercontent.com/33997503/157394175-ced36c31-090d-49c6-a2bb-14d6b4b8513f.png)

**Comment by Cnilton** [comment]
Hi @isthisshivam, can you please inform how did your reproduce this issue and also versions of this lib and of react-native-reanimated?

**Comment by Cnilton** [comment]
@isthisshivam, any update?
