### ISSUE TITLE
not working onChange

### ISSUE THREAD

**Issue by Luhkas27** [Cnilton/react-native-floating-label-input#115]
Good afternoon, the input is not working correctly on his onChange, I have already updated both the lib here and the reanimated to see if it came back and nothing worked.

https://user-images.githubusercontent.com/41193788/158252720-dfc047e6-1da0-4139-b7eb-1cafb37d394e.mov

**Comment by Cnilton** [comment]
Hi @Luhkas27, I think you are using the wrong property. For the input text value change you should use `onChangeText` prop.

**Comment by Luhkas27** [comment]
then follow the component code:

 const handleChange = (value: any) => {
    let stageValue = value
    if (maskType && masks[maskType]) stageValue = masks[maskType](value)
    if (onChange) onChange(stageValue)
  }
  return (
    <>
      <S.Container>
        <S.WrapperInput>
          {icon && <IconLock />}
          <S.Input
            ref={(r) => {
              if (ref && r?._inputElement) {
                ref.current = r._inputElement
              }
            }}
            {...(onBlur ? { isFocused, onBlur } : {})}
            {...(onFocus ? { onFocus } : {})}
            label={label}
            value={(maskType && masks[maskType](value)) || value}
            hintTextColor={theme.pallete.maskInput}
            maskType={maskType}
            mask={mask}
            maxDecimalPlaces={maxDecimalPlaces}
            keyboardType={keyboardType}
            multiline={multiline}
            maxLength={maxLength}
            hint={placeholder}
            autoCapitalize="none"
            autoCorrect={false}
            editable={editable}
            onChangeText={handleChange}

**Comment by Cnilton** [comment]
I'm sorry, but part of the code that is relevant for this probable issue is missing as being used in:

```javascript 
const handleChange = (value: any) => {
   let stageValue = value
   if (maskType && masks[maskType]) stageValue = masks [maskType] (value)
   if (onChange) onChange(stageValue)
}
```

Can you please inform the usage of the `masks`, `maskType`, and `onChange`?

**Comment by Cnilton** [comment]
@Luhkas27, any update?

**Comment by Luhkas27** [comment]
@Cnilton we couldn't come up with a concrete solution and decided to make another input component by hand

**Comment by Cnilton** [comment]
I'm sorry to hear that, but if you change your mind, I'll be right here!
