### ISSUE TITLE
currency as a masktype broken

### ISSUE THREAD

**Issue by adamsythe** [Cnilton/react-native-floating-label-input#119]
Two issues when i use currency as a masktype.  Firstly users cant backspace at all and secondly textInput just has NaN after user types more than 4 characters

**Comment by Cnilton** [comment]
Hi @adamsythe, I'll test it out later. What version are you using?

**Comment by adamsythe** [comment]
"react-native-floating-label-input": "^1.3.13",

"react-native-floating-label-input": {
      "version": "1.3.13",
      "resolved": "https://registry.npmjs.org/react-native-floating-label-input/-/react-native-floating-label-input-1.3.13.tgz",
      "integrity": "sha512-vTfwiT4e6/9BdzFuvVo9Bg1Lj0Kle22GivoWzmSII1ZwvH56sjZvKKWpBfomNXy9VIneK3lky+l2Xb40+hsQMw==",
      "requires": {}
    },

**Comment by Cnilton** [comment]
@adamsythe, could you please try new version? I changed currency masking back to the old form.

**Comment by Cnilton** [comment]
@adamsythe, any updates with the new version?

**Comment by adamsythe** [comment]
thanks it works :). Would be nice if we could have a space as divider as well :)

**Comment by Cnilton** [comment]
@adamsythe,  maybe you could use spacing without currency mask, but I'm glad it's working now! I'll be closing this issue now!

**Comment by justdan0227** [comment]
This appears to be broken again in "react-native-floating-label-input": "^1.4.2", as you can enter in more then 2 digits past the decimal point
