### ISSUE TITLE
Android : Text Overlapping issue

### ISSUE THREAD

**Issue by bgrgit** [Cnilton/react-native-floating-label-input#120]
Text getting overlapping with placeholder text. Can you help me to fix this
<img width="304" alt="Screenshot 2022-04-07 at 7 56 28 PM" src="https://user-images.githubusercontent.com/31758716/162222386-fa125fb9-40b7-48a1-abd4-7a53bb300c97.png">
s

Upgrading to
    "react-native-floating-label-input": "^1.3.13",

After upgrading to above version, I am getting below issue. Firstname placeholder hidden which I entered the text

<img width="424" alt="Screenshot 2022-04-07 at 7 57 47 PM" src="https://user-images.githubusercontent.com/31758716/162225267-1b61f648-70fe-4870-8d3e-5643c5ed425a.png">

**Comment by Cnilton** [comment]
Hi @bgrgit, I'm sorry, but I couldn't understand your issue.. Could you please elaborate? And if possible, post your code?

**Comment by bgrgit** [comment]
Hi @Cnilton  , In second Image , First name field have text but not visible. And sometimes it's getting overlapping.

**Comment by Cnilton** [comment]
@bgrgit any updates?
