### ISSUE TITLE
Multiline Android React native always focus last charater not Top

### ISSUE THREAD

**Issue by harshal311989** [Cnilton/react-native-floating-label-input#121]
hi team,

I used this plugin in my application and i add multimine={true} for support multiple line in my text filed so when i run application in android and i set long text on that it is always focus at bottom which i add last not focus top . Refer my video it will give better idea

https://user-images.githubusercontent.com/75067288/163573654-45460c5f-81a1-408f-88ea-27006968126b.mov

Any idea how can i fix this ? in iOS it is working fine issue only in Android .

My code as below

       `export default function App() {
        const [cont, setCont] = useState('fskjhfsfskjhfsdkjfhfskjhfsdkjfhfskjhfsdkjfhfskjhfsdkjfhfskjhfsdkjfhfskjhfsdkjfhdkjfh, 
       fskjhfsdkjfh, fskjhfsdkjfh , fskjhfsdkjfh,  fskjhfsdkjfh, ,fskjhfsdkjfh fskjhfsdkjfh hdsfdskjfhdsjkfhsdfhdk dsjfhdskjfhsdjkfhdjhfk 
      shfdkjhf dfhdskjfhdskhfdjksfhdjkhfkjsdfhdksjhfdksjhf ds');
  
      return (
       <View style={{ padding: 50, flex: 1, backgroundColor: '#fff',  }}>
         <FloatingLabelInput
          label={'label'}
          multiline
          inputStyles={{minHeight:30, maxHeight:80, }}
          value={cont}
          onChangeText={value => {
             setCont(value)
     
            }}
         />
       </View>
       );
     }`

**Comment by Cnilton** [comment]
Hi @harshal311989, I'm afraid this is the default behavior on android. But you could get over it with the *selection* prop and maybe a boolean useState variable for controlling when render has occured and then setting selection to undefined like:

```javascript
// ...
const [value, setValue] = useState('fskjhfsfskjhfsdkjfhfskjhfsdkjfhfskjhfsdkjfhfskjhfsdkjfhfskjhfsdkjfhfskjhfsdkjfhdkjfh, 
   fskjhfsdkjfh, fskjhfsdkjfh , fskjhfsdkjfh,  fskjhfsdkjfh, ,fskjhfsdkjfh fskjhfsdkjfh hdsfdskjfhdsjkfhsdfhdk dsjfhdskjfhsdjkfhdjhfk 
  shfdkjhf dfhdskjfhdskhfdjksfhdjkhfkjsdfhdksjhfdksjhf ds')

const [rendered, setRendered] = useState(false)

useEffect(()=>{
setRendered(true)
},[]}

<FloatingLabelInput
multiline
value={value}
onChangeText={setValue}
selection={!rendered? {start:0, end:0}: undefined}
/>

// ...
```

**Comment by harshal311989** [comment]
@Cnilton yes working .

**Comment by Cnilton** [comment]
Thanks for the quick response @harshal311989! I'll close this issue now.
