### ISSUE TITLE
this library freezes up my app

### ISSUE THREAD

**Issue by ceyanesb** [Cnilton/react-native-floating-label-input#123]
This library freezes up my app, back swipe doesn't work as well as the hot reload!

**Comment by Cnilton** [comment]
Hi @ceyanesb, what version are you using? Did you follow the steps for installation?

**Comment by ceyanesb** [comment]
Yes. I followed the instructions on installing react native reanimated and everything else but it still freezes the app, it displays and you can type but hit reload won't work and swipe back gesture also won't work

**Comment by Cnilton** [comment]
@ceyanesb, do this issue still occur? If it does, could you please provide more information, like react-native version, reanimated version, and error message?
