### ISSUE TITLE
library is causing android to crash

### ISSUE THREAD

**Issue by adamsythe** [Cnilton/react-native-floating-label-input#125]
When i run this on an android device it throws the following error

TypeError: Cannot read property 'FloatingLabelInput' of undefined

this is how I am importing

import { FloatingLabelInput } from 'react-native-floating-label-input';

and then if i use it at all it crashes.  Works perfectly on IOS.

I test a production build and it doesn't crash in production only in development

**Comment by Cnilton** [comment]
Hi @adamsythe, what version are you using? Did you run yarn before running the app?
