### ISSUE TITLE
Typing not working (v1.3.13)

### ISSUE THREAD

**Issue by designsheikh** [Cnilton/react-native-floating-label-input#129]
After correctly installing the library and adding it to my project - clicking on the input provides the correct floating label animation. However, when typing inside the input, the character is automatically deleted both on simulator and on device and the input remains empty. 

Awaiting replies

Thanks

![120CF9D6-78D1-42CF-AD0D-9C1D4D179B6E](https://user-images.githubusercontent.com/60884506/173260468-d9dd122e-0765-4690-9f4c-829742cf44ea.GIF)

**Comment by Cnilton** [comment]
Hi @designsheikh, can you please post the code used on floating label input? It seems like maybe you forgot to use onChangeText prop.

**Comment by designsheikh** [comment]
> Hi @designsheikh, can you please post the code used on floating label input? It seems like maybe you forgot to use onChangeText prop.

Hi @Cnilton - This solved the issue. I was missing both value and onChangeText. 

Thakn you for your prompt response!
