### ISSUE TITLE
Enhancement: Update Currency Mask Rules

### ISSUE THREAD

**Issue by psenechal** [Cnilton/react-native-floating-label-input#13]
I noticed the currency mask allows multiple decimals and the number of decimal places is also not limited.

I think it would help to only allow one use of the decimal and default the number of decimal places to 2 with an override available for currencies that have zero or 3.

I might see if I can work up a pull request for this if I have time.

**Comment by Cnilton** [comment]
So, I denied the pull request as you recommended, but now I don't remember if your updates for masks were taken already.

**Comment by psenechal** [comment]
Yes...the first pull request that you merged ended up having both changes in it, so you should have the updated currency mask rules and the multiline functionality. Rookie mistake with my branching there...sorry about the confusion.

**Comment by psenechal** [comment]
You're right...the code is not in there.
I'll create another pull request with the update for the currency mask.

**Comment by Cnilton** [comment]
Ok, I'll be waiting for your pull request

**Comment by Cnilton** [comment]
I just merged your pull request, and I'll fix a few little bugs and launch the next version on npm, thanks for your contribution!
