### ISSUE TITLE
Autofill phone number - remove +91 or country code

### ISSUE THREAD

**Issue by srithar21** [Cnilton/react-native-floating-label-input#132]
Hi ,

I am facing the issue in autofill phone number from the suggestion. Here, not able to detect that selection because need to remove the +91 or any country code.

OS: iOS 15.5
React native: 67.2

**Comment by Cnilton** [comment]
Hi @srithar21, I'm sorry, but I couldn't understand your issue with this lib. What exactly is happening with the input, and what version of this lib are you using?

**Comment by Cnilton** [comment]
@srithar21 Any updatas?

**Comment by srithar21** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/1001455/174905065-a14db107-7f8f-407e-93c7-909a93e191a8.png)
Hi Cnilton,

 I am asking about any way to detect when number selected from the keyboard above? Highlighted in red color.
