### ISSUE TITLE
Changing label color is a bit counter intuitive

### ISSUE THREAD

**Issue by BuXXe** [Cnilton/react-native-floating-label-input#134]
I tried to change the color of the label by using the label_styles property given in your documentation. If you use the properties you gave in your example (backgroundColor: '#fff', paddingHorizontal: 5) they work as expected. If you now try to change the text color of the label by using the commonly known property (ex. color="red") it doesnt seem to do anything. 

I solved this issue by using the  customLabelStyles={{ colorFocused: 'red', colorBlurred:'green'}} property. It took me a few minutes to find this and I saw a closed issue related to label coloring problems, so i guess this issue isnt only on my side.

Dont think it is necessary to change something implementation vise but maybe a note in the documentation would be helpful. Still, thanks for your work :)

**Comment by Cnilton** [comment]
hi @BuXXe, could you please open a PR for adding this to the readme section? It would be of great help!

**Comment by BuXXe** [comment]
#137 Done :)

**Comment by Cnilton** [comment]
Thanks, I'll close this now 🚀
