### ISSUE TITLE
Tried to synchronously call anonymous function from a different threat

### ISSUE THREAD

**Issue by baranngungor** [Cnilton/react-native-floating-label-input#135]
I can import and see the Floating Label Input but I faced error that say:

Occurred in workout location: node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts(492:18)

Possible solutions are:
a)If you want to synchronously execute this method, mark it as a Worklet
b)If you want to execute this method on the JS thread, wrap it using runOnJS

How can I fix that? What should I do?

**Comment by asfandyarsheikh** [comment]
+1

**Comment by Cnilton** [comment]
Hi @baranngungor, did you install the reanimated lib at v2?
