### ISSUE TITLE
defaultValue  props are not working

### ISSUE THREAD

**Issue by bibekkotal** [Cnilton/react-native-floating-label-input#136]
<FloatingLabelInput
                                        label='Full Name'
                                        defaultValue={userdata.full_name}   <---------- give me a solution asap
                                        staticLabel
                                        hintTextColor={Colors.placeholder}
                                        containerStyles={
                                            EditProfileStyles.FloatingLabelInputContainer
                                        }
                                        customLabelStyles={EditProfileStyles.customLabelStyles}
                                        labelStyles={EditProfileStyles.labelStyles}
                                        inputStyles={EditProfileStyles.inputStyles}
                                        onChangeText={(value) => {
                                            setName(value);
                                        }}
                                        selectionColor={Colors.primary}
                                    />

**Comment by Cnilton** [comment]
Hi @bibekkotal, I'm sorry, but there is no defaultValue prop. Could you please try using *value* prop?

**Comment by Cnilton** [comment]
@bibekkotal, any update?
