### ISSUE TITLE
Feature Request: disabled

### ISSUE THREAD

**Issue by anarkrypto** [Cnilton/react-native-floating-label-input#138]
Hi! Congratulations on the excellent component.

I would like to request the implementation of the 'disabled' parameter.

I think it is greatly missed.

```<FloatingLabelInput disabled={true || false} ... />```

**Comment by Cnilton** [comment]
Hi @anarkrypto, by disabled you mean changing the style of input and texts or disabling the touch and insertion of text?

**Comment by sebasbeleno** [comment]
Hey @anarkrypto.

If you want to prevent the touch and insertion of text on the input you can use `editable` as a prop. The component extends `TextInputProps` from react-native.

**Comment by anarkrypto** [comment]
@Cnilton, I mean both: disable text input and change the style

**Comment by Cnilton** [comment]
@anarkrypto, so for changing style, I think the best would be if it was treated directly in your project because the disabled style isn't the same for everybody. And about disabling the input you do as @sebasbeleno said above.
