### ISSUE TITLE
setNativeProps is not a function

### ISSUE THREAD

**Issue by michal4511** [Cnilton/react-native-floating-label-input#143]
I replaced my existing input with FloatingLabelInput, just I have a problem with the next part of the code that changes the default fontFamily. The simulator renders an error, that you can see in the picture: 
<img width="606" alt="Screenshot 2022-12-06 at 15 01 55" src="https://user-images.githubusercontent.com/69518903/205947415-3cd23b9d-b9ea-4bd2-923f-7a959d2d9981.png">
<img width="377" alt="Screenshot 2022-12-06 at 14 50 02" src="https://user-images.githubusercontent.com/69518903/205947463-a9ef4209-8fd1-4626-bf80-d1ae18661606.png">

**Comment by Cnilton** [comment]
Hi @michal4511, you could set any style without setting by ref. You could set font family by using inputStyles or labelStyles.

**Comment by Cnilton** [comment]
@michal4511, any updates?
