### ISSUE TITLE
If label is focused it has shadow background

### ISSUE THREAD

**Issue by michal4511** [Cnilton/react-native-floating-label-input#144]
If I click on the label in the input the label has a shadow background. Do you know how can I remove this effect? 
<img width="300" alt="Screenshot 2022-12-06 at 15 58 01" src="https://user-images.githubusercontent.com/69518903/205961043-13c12a51-933b-4a0c-b063-bca450384f49.png">

**Comment by Cnilton** [comment]
Hi @michal4511, I'll check it out soon!

**Comment by Sermanbilotil** [comment]
Any news?

**Comment by Sermanbilotil** [comment]
Also have this problem. Version 1.4.2

**Comment by michal4511** [comment]
> Hi @michal4511, I'll check it out soon!

**Comment by michal4511** [comment]
Did you have a look at this problem @Cnilton ?

**Comment by peterlazar1993** [comment]
@michal4511 You can apply this [patch](https://github.com/Cnilton/react-native-floating-label-input/pull/150) and it will fix the issue.
