### ISSUE TITLE
Update to Reanimated 3.x

### ISSUE THREAD

**Issue by KevinvdBurg** [Cnilton/react-native-floating-label-input#152]
Hello,

I'm curious if there are plans to upgrade Reanimated to version 3.x on the roadmap?
I'm keen to incorporate it into my project.

Kevin

**Comment by Cnilton** [comment]
Hi @KevinvdBurg, I'll try to add it to a new version soon!

**Comment by Cnilton** [comment]
@KevinvdBurg just tried with a fresh project and it worked, so it's compatible out of the box!

![image](https://github.com/Cnilton/react-native-floating-label-input/assets/40298250/c6c70a50-47f5-4709-a5c7-54daf7fda930)

**Comment by KevinvdBurg** [comment]
Nice, I thought because the README specially mansions Reanimated 2.x my assumption was that it was not updated for Reanimated 3.x.

Thanks!
