### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by edwardigates** [Cnilton/react-native-floating-label-input#16]
What if I want the floating label to be on the right side for hebrew/arabic?
I tried to play with `containerStyles`, `labelStyles` and `inputStyles`, but I couldn't set the label to appear from the right.
Does this library support rtl, how can I achieve it?

Edit:
The only way I could put the label on the right is this styling:
`labelStyles={{width:'100%', textAlign:'right'}}`

But I'm not sure this is the correct way to do it.

**Comment by Cnilton** [comment]
Hi @edwardigates, I'm not sure, but I think that there is a way to do it using customLabelStyles prop. I'll look into it!

**Comment by Cnilton** [comment]
So, I can confirm with the following code that RTL is already supported with a few extra steps:

```javascript
import React, {useState} from 'react';
import {ScrollView} from 'react-native';
import {FloatingLabelInput} from 'react-native-floating-label-input';

import {I18nManager} from 'react-native';  // required
I18nManager.forceRTL(true);  // required

function HomeScreen() {
  const [rtl, setRtl] = useState('');

  return (
    <ScrollView
      keyboardShouldPersistTaps="handled"
      contentContainerStyle={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'stretch',
        margin: 30,
      }}>
      <FloatingLabelInput
        autoCapitalize="words"
        label="RTL"
        value={rtl}
        labelStyles={{textAlign: 'right'}} // required
        inputStyles={{textAlign: 'right'}} // required
        customLabelStyles={{leftFocused: -16, leftBlurred: -16}} // this is just because the label is too close of the border
        onChangeText={(value) => setRtl(value)}
      />
    </ScrollView>
  );
}

export default HomeScreen;
```

<img src ="https://i.imgur.com/yBbQM1w.gif" width="40%"/>

**Comment by edwardigates** [comment]
@Cnilton Thanks.

**Comment by Cnilton** [comment]
@edwardigates You're welcome!
