### ISSUE TITLE
Floating label with drop down - Feature suggestion

### ISSUE THREAD

**Issue by edwardigates** [Cnilton/react-native-floating-label-input#17]
Is there any plans to add floating labels with drop downs (selects) like [this](https://material-ui.com/components/selects/) ?

**Comment by Cnilton** [comment]
@edwardigates, not in this component, I'm sorry. That funcionality relies on a Picker as base component, and this library relies on TextInput.

Although, this is a pretty good feature for @react-native-community/picker, if it's not already implemented. Can you please check? If they don't intend on adding this funcionality, I think I might be able to create a custom picker library with that funcionality.
