### ISSUE TITLE
mask and maskType

### ISSUE THREAD

**Issue by edwardigates** [Cnilton/react-native-floating-label-input#19]
I have a question about using mask and maskType.
I want to use the text input for credit card input, I set the maskType to 'card', but what should be the mask for the card?
I want it to appear divided into groups of 4 digits. Can I achieve it with the properties?

**Comment by Cnilton** [comment]
Hi @edwardigates,

Yes, you can achieve it with the properties. Try the following:

```javascript

<FloatingLabelInput
        label="Card"
        value={card}
        maskType="card"
        mask="9999 9999 9999 9999"
        keyboardType="numeric"
        onChangeText={value => setCard(value)}
      />

```

Hope this helps.
