### ISSUE TITLE
onBlur is not working

### ISSUE THREAD

**Issue by DodlaRajasekharReddy1995** [Cnilton/react-native-floating-label-input#2]
hi , thanks for the wonderful library ...it helped a lot. But in this library onBlur is not working . I want to validate the entered input when the input field gets out of focus. Actually we can acheive this using onBlur for normal input field , but i am not able to find any props to achieve this in this library .

is there any prop to achieve this...Please help me out with this.

**Comment by Cnilton** [comment]
Hi, indeed native props are not available still.. I'll work on it.

**Comment by Cnilton** [comment]
@DodlaRajasekharReddy1995, this issue has been fixed at the last update, could you please check it out?
