### ISSUE TITLE
How to set custom password Hide icon?

### ISSUE THREAD

**Issue by AvitaliyaORG** [Cnilton/react-native-floating-label-input#20]

**Comment by Cnilton** [comment]
Hi @AvitaliyaORG, I see.. this is an issue, I've forgotten to add the "hide" custom icon prop. I'll work on it. Tomorrow I'll create a new version.

**Comment by Cnilton** [comment]
@AvitaliyaORG, can you please try the new version 1.2.9, and verify it?
