### ISSUE TITLE
How to maximize width of container?

### ISSUE THREAD

**Issue by idiglove** [Cnilton/react-native-floating-label-input#21]
<img width="321" alt="Screen Shot 2020-11-13 at 9 17 39 AM" src="https://user-images.githubusercontent.com/29911508/99016054-3aaf8880-2591-11eb-87ff-fff3e7735bd4.png">

I want my input container to not have any spaces on the sides. How to achieve this?
I have added margin:0 and padding: 0 in containerStyles but doesnt work

thanks

**Comment by Cnilton** [comment]
Hi @idiglove, I think that my default styles are making this behavior. Can you please try adding paddingHorizontal:0 also?
