### ISSUE TITLE
ispassword= true is not working in android

### ISSUE THREAD

**Issue by singhvishal802** [Cnilton/react-native-floating-label-input#22]
<FloatingLabelInput
              label="Password"
              value={password}
              isFocused={isPassFocused}
              labelStyles={{ color: isPassFocused ? '#B6254E' : '#333333', fontSize: wp("4%"), marginLeft: 25 }}
              containerStyles={{ borderWidth: 0, paddingLeft: 35, height: wp("15%"), }}
              onFocus={() => {
                setIsPassFocused(true);
              }}
              onBlur={() => {
                password === '' && setIsPassFocused(false);
              }}
              isPassword={true}
              inputStyles={{ borderBottomWidth: 0, borderBottomColor: 'grey' }}
              onChangeText={value => setPassword(value)}
            />

**Comment by Cnilton** [comment]
Hi @singhvishal802, I'll be testing this by tomorrow, and if this is reproducible I'll provide a workaround or fix

**Comment by Cnilton** [comment]
So, using your code "isPassword" prop is working as expected. As you see in the image, everything is working:

![print issue flip](https://user-images.githubusercontent.com/40298250/99877438-06654900-2bdd-11eb-918e-48d41db2d842.png)

Could you please elaborate if this issue remains happening to you?
