### ISSUE TITLE
Use string instead of images for password field

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#24]
Right now in the Readme file you have
```
import showPassword from '../assets/images/yourImage';
import hidePassword from '../assets/images/yourImage2';
// ...
<FloatingLabelInput
  label="Password"
  value={password}
  isPassword={true}
  onChangeText={text => setPassword(text)}
  customShowPasswordImage={showPassword}
  customHidePasswordImage={hidePassword}
/>
```

Where We need to pass an image when a password field is used, can we add new params and use strings (<Text> component) instead?  something like `Show and Hide` could be use it.

**Comment by Cnilton** [comment]
Hi @Diego-Franco,  I'll be adding this in the next version, ok? Soon, I'll close this with this functionality.

**Comment by Cnilton** [comment]
Can you please check out the new props that were added in version 1.2.13? Everything you need to know is in the README.md, so you can just open this lib homepage and check 🎉🎉

**Comment by Diego-Franco** [comment]
This is working now, thank you!
