### ISSUE TITLE
Overriding onBlur and onFocus blocks label animation 

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#25]
Using: 
```
const { isFocused } = this.state;
<FloatingLabelInput
	ref={this.inputRef}
	label={placeholder}
	value={value}
	isFocused={isFocused}
	onChangeText={this.onChangeText}
	onFocus={this.onFocus}
	onBlur={this.onBlur} />
```

it blocks the animation for the label and it doesn't move at all

<Img src="https://user-images.githubusercontent.com/5623933/101533198-62083400-394a-11eb-9adc-b2850b1a29e3.gif" width=500/>

**Comment by Cnilton** [comment]
Hi @Diego-Franco, can you please test with version 1.2.13? Thanks

**Comment by Diego-Franco** [comment]
This is working in 1.2.13 🎉

**Comment by Uzef1997** [comment]
I am using 1.3.4 still getting same issue 

https://user-images.githubusercontent.com/45681786/108326762-a50b4100-71f0-11eb-818f-851432008dd9.mov
