### ISSUE TITLE
Predefined Value in the TextInput Field don't trigger the animation for the label

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#28]
This one is easy to reproduce, if you use:
```
<FloatingLabelInput
	label="Login"
	value="This is a value"
	onChangeText={nValue => setValue(nValue)}
	customLabelStyles={CUSTOM_LABEL_STYLE} />
```

the value is overlapping the label, and the label doesn't animate if the value exists in the component

![Screen Shot 2020-12-08 at 5 22 39 PM](https://user-images.githubusercontent.com/5623933/101561420-2a18e500-397a-11eb-8cc8-44097da5a162.png)

**Comment by Cnilton** [comment]
Hi @Diego-Franco, can you please check the new version 1.2.13 if this is still occurring? This is a regression from the last update I made before.

**Comment by Diego-Franco** [comment]
I can say this is still happening 😞 some times is not displaying the value and if the animation is triggered the floating label goes all the way out of the container 

![Screen Shot 2020-12-09 at 11 09 22 AM](https://user-images.githubusercontent.com/5623933/101675841-2f743f00-3a0f-11eb-9b28-2ace3cf24e40.png)

**Comment by Cnilton** [comment]
Are you sure it's not the customLabelStyles that are making this behavior? Can you please try without the customLabelStyles? Or at least provide it here for me to reproduce it.

**Comment by Diego-Franco** [comment]
you're right it was the CustomLabelStyles causing the problem, but the floating label is still going outside of the container
![Screen Shot 2020-12-09 at 11 35 34 AM](https://user-images.githubusercontent.com/5623933/101678478-d7d7d280-3a12-11eb-984e-5f3c95e3c794.png)

**Comment by Cnilton** [comment]
Okay, can you please post for reproducibility test your FloatingLabel Component?

**Comment by Diego-Franco** [comment]
Here's my code
```
<FloatingLabelInput
	ref={this.inputRef}
	label={placeholder}
	value={value}
	onChangeText={this.onChangeText}
	onFocus={this.onFocus}
	onBlur={this.onBlur}
	isFocused={isFocused}
	onSubmit={this.onSubmit}
	keyboardType={keyboardType}
	editable={!disabled}
	containerStyles={containerStyle}
	customLabelStyles={CUSTOM_LABEL_STYLE}
	labelStyles={styles.labelStyle}
	inputStyles={styles.inputStyle}
	/>
```

my custom_label_style and container style:
```
const CUSTOM_LABEL_STYLE = {
	fontSizeFocused: CKTextSize.SMALL,
	fontSizeBlurred: CKTextSize.BASE,
	colorBlurred: CKColors.darkGrey,
	colorFocused: CKColors.darkGrey,
};

container: {
		height: 64,
		borderWidth: 2,
		borderRadius: 8,
		alignContent: 'center',
		paddingVertical: 16,
		paddingHorizontal: 16,
	},

```

**Comment by Cnilton** [comment]
Thank you, I'll confirm reproducibility and debug this.

**Comment by Cnilton** [comment]
Sorry, but I'll need more info.. with the provided data, I couldn't reproduce the bug.

<img src ="https://i.imgur.com/BzJxXig.gif" width="40%"/>

```javascript
<FloatingLabelInput
        // ref={this.inputRef}
        label={'PlaceHolder'}
        autoFocus
        value={phone}
        onChangeText={(value) => setPhone(value)}
        onFocus={focus}
        onBlur={blur}
        isFocused={focused}
        // onSubmit={this.onSubmit}
        // keyboardType={keyboardType}
        // editable={!disabled}
        containerStyles={{
          height: 64,
          borderWidth: 2,
          borderRadius: 8,
          alignContent: 'center',
          paddingVertical: 16,
          paddingHorizontal: 16,
        }}
        // customLabelStyles={CUSTOM_LABEL_STYLE}
        // labelStyles={styles.labelStyle}
        // inputStyles={styles.inputStyle}
      />
```

**Comment by Diego-Franco** [comment]
you have to set value, if you change value="this is a value" you will see the problem

**Comment by Cnilton** [comment]
I see. Indeed you were right, there was one place where I forgot to divide by 2 the animated height. Could you please test version 1.2.14? Thanks!

**Comment by Diego-Franco** [comment]
this is fixed!
