### ISSUE TITLE
Add left component to the floating input 

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#29]
It would be nice if we can add a left component to the floating input, then we can create components like: 

![Screen Shot 2020-12-09 at 11 42 20 AM](https://user-images.githubusercontent.com/5623933/101679165-ca6f1800-3a13-11eb-846c-2dc5183a5122.png)

**Comment by Cnilton** [comment]
Hi @Diego-Franco, that is a good idea, I'll add this feature in the next version. Thanks

**Comment by Cnilton** [comment]
Feature added in version 1.2.16 🎉🎉. Can you please test it?

**Comment by Cnilton** [comment]
I didn't understand what you mean by extra padding. Can you clarify what is the issue?

**Comment by Diego-Franco** [comment]
it looks like it was the styles, we're good! Thank you!
