### ISSUE TITLE
Make Component Props public

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#30]
Right now we have `interface Props` in the component, if people is going to use this component and want to extends from this, we should be able to export the props instead of copying in the code.

We have: `interface Props extends TextInputProps ` 

We can create: `export interface FloatinLabelInputProps extends TextInputProps`

**Comment by Cnilton** [comment]
Hi @Diego-Franco, I see your point. Is this really useful on a Typescript project?

**Comment by Diego-Franco** [comment]
yes, I think is useful, instead of creating a copy of the props you have in the lib, I can create something like:

type InputField extends FloatinLabelInputProps {
... extraProps
{

and I'll have the TextInputProps too for free

**Comment by Cnilton** [comment]
Can you please try it out on version 1.2.14? Thanks in advance!

**Comment by Diego-Franco** [comment]
I think you forgot to make it public, you just added export in the index

**Comment by Cnilton** [comment]
Hmm, I see. I'll fix it in the next version. Thanks!

**Comment by Cnilton** [comment]
@Diego-Franco, can you please test version 1.2.15?

**Comment by Diego-Franco** [comment]
this if fixed! Thank you!
