### ISSUE TITLE
Enable autoFocus for InputComponent

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#31]
Right now we have `setFocus` function, but we don't have a way to set autoFocus for the input field, we can added because we have the TextInput props.

**Comment by Cnilton** [comment]
Hi @Diego-Franco, you already can use the *autoFocus* prop. Try it out!

**Comment by Diego-Franco** [comment]
sorry, that's true, I forgot about the TextInputProps, I'll close this
