### ISSUE TITLE
Use hint prop when non staticLabel is use it

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#32]
Right now, the prop `hint` is only use it when staticLabel is used in the code, we can use hint too when we use the normal floating label, for example:

Entering a date or birth we should display `date of birth` in the label and the hint could be `mm/dd/yyyy` to explain the users the input format.

**Comment by Cnilton** [comment]
Hi @Diego-Franco, if `hint` was available when it isn't `staticLabel` we would have overlapped label and hint. What do you suggest in that case? Showing the hint when the input is focused and has no text? I don't think that is quite useful.

**Comment by Diego-Franco** [comment]
Yes, it was I suggest, then we can create something like:
![Screen Shot 2020-12-11 at 9 32 11 AM](https://user-images.githubusercontent.com/5623933/101935433-f1545800-3b93-11eb-94c2-42fbb4cce6da.png)

**Comment by Cnilton** [comment]
Ok, I'll add this soon then!

**Comment by Cnilton** [comment]
Can you check version 1.2.16?

**Comment by Diego-Franco** [comment]
this if fixed!

**Comment by Edmundoacosta** [comment]
@Cnilton hello caio sorry to open this issue again but, can we have a hint always visible option? I want to create a date input like show below but with the placeholder always there.

**Comment by Cnilton** [comment]
Hi @Edmundoacosta, I'm sorry but i didn't understand. If you want the hint also to be always visible, couldn't you just add it to the  label? The hint is just the placeholder for helping the user to understand the pattern of some field data. 

If I'm correct, you want something like 
![image](https://user-images.githubusercontent.com/40298250/192362336-1325955e-3104-4017-a3f4-7ac8e1dbb927.png)
but you want the hint to always be visible either, right?
