### ISSUE TITLE
Typescript issue with opacity value

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#34]
in the Line 350, we have opacity props, in Typescript is returning a warning, this is the warning:

```
Type 'number | AnimatedInterpolation' is not assignable to type 'number | undefined'.
  Type 'AnimatedInterpolation' is not assignable to type 'number'

The expected type comes from property 'opacity' which is declared here on type 'TextStyle'
```

**Comment by Cnilton** [comment]
Hi @Diego-Franco, actually opacity accepts both `AnimatedInterpolation` and `Animated.Value`. I don't know how to fix it unless to ask typescript maintainers to update it.

**Comment by Diego-Franco** [comment]
are you sure? let me explain better, we have:

```
const style: TextStyle = {
  opacity: staticLabel ? opacityAnimated.interpolate({
      inputRange: [0, 1],
      outputRange: [0, 1]
    }) : labelStyles?.opacity ? labelStyles.opacity : setGlobalStyles?.labelStyles?.opacity ? setGlobalStyles.labelStyles.opacity : 1,
 }
```
Where TextStyle extends from ViewStyle, and if you take a look to the @types/react-native ViewStyle interface, you can see, they have `opacity?: number`. Not sure if you got the same error in your side.

Here's a screenshot:
![Screen Shot 2020-12-11 at 1 24 39 PM](https://user-images.githubusercontent.com/5623933/101956446-7bacb400-3bb4-11eb-9e86-5a0d40329f59.png)

**Comment by Diego-Franco** [comment]
PR created!
