### ISSUE TITLE
Label animation is not smooth 

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#36]
This is more a question/request, right now when the input field is not focused and gain the focus, we're just changing the fontSize of the label and then we use translateX and translateY.

could be possible to add a scale for the fontSize? then the animation will look smoother. 

I'm trying to make it work on my side, but if anyone can help with this too would be nice

**Comment by Cnilton** [comment]
Hi @Diego-Franco, actually I was thinking of adding animation to the *fontSize* recently, but this week has been a little rough so I didn't have the time. I'll see if this weekend I can work on it. Thanks for the observation!

**Comment by Diego-Franco** [comment]
Do we have any update? Also are you planning to use the animated api from reach native or are you planing to change to a different approach?

**Comment by Cnilton** [comment]
Hi @Diego-Franco, can you please test version 1.3.0?

**Comment by Cnilton** [comment]
I'm closing this issue due to no response.
