### ISSUE TITLE
Currency format not working well

### ISSUE THREAD

**Issue by tcagkansokmen** [Cnilton/react-native-floating-label-input#38]
I'm typing "100" and It stucks on "1,00" format.
(I make currencyDivider=".")

To change 1,00 to 100,00, I have to click on begining of the input and start typing.
But that's not good for UX.

How can I use it well?

**Comment by Cnilton** [comment]
Hi @tcagkansokmen, I couldn't see any problem trying to reproduce... 
What I tested: input 1, then 0, then 0, resulted in 100
```javascript
<FloatingLabelInput
        label="Currency"
        hint="5.800,00"
        value={cont}
        currencyDivider="."
        labelStyles={{backgroundColor: '#fff',}}
        onChangeText={(val) => setCont(val)}
        maskType="currency"
      />
```

May you please provide some code for reproducibility?

**Comment by Cnilton** [comment]
@tcagkansokmen, can you please elaborate so I can understand the bug?

**Comment by Cnilton** [comment]
I'll be closing this issue due to no response.
