### ISSUE TITLE
customLabelStyles not working

### ISSUE THREAD

**Issue by mariomnesp** [Cnilton/react-native-floating-label-input#4]
Hi, thanks for this library!
So, the issue is customLabelStyles is expecting an object that can't really be matched, because it's expecting it's children's types to be the intended default values. When it receives the props on index.tsx it looks like this, when it should be specifying numbers and strings:
![image](https://user-images.githubusercontent.com/69463294/90155422-a9e2ca00-dd61-11ea-9996-9abb96114de8.png)

Then what happens in my code is I try to pass the values and this comes up:
![image](https://user-images.githubusercontent.com/69463294/90155643-f1695600-dd61-11ea-92bc-956dd2ad27e4.png)

**Comment by Cnilton** [comment]
Hello, @mariomnesp! 

Thank you for contributing! I just fixed those mistakes. Could you please try updating and checking if it is still reproducible?

**Comment by Cnilton** [comment]
I'll close this issue as no response was given and as it's not reproducible anymore to me.
