### ISSUE TITLE
Problemas com leftFocused & topFocused

### ISSUE THREAD

**Issue by Franklyn-S** [Cnilton/react-native-floating-label-input#40]
leftFocused & topFocused não fazem sentido se staticLabel for true, por que só teria left e top, não existiria focused nesse caso.

leftFocused & topFocused não funcionam no customLabelStyles se staticLabel for false, caso default dele.

**Comment by Cnilton** [comment]
Oi @Franklyn-S, você pode mostrar um exemplo? Não consegui reproduzir esse problema na versão atual desta biblioteca. Você confirmar também a versão que está utilizando?

**Comment by Franklyn-S** [comment]
Deixa pra lá, deu certo, era só pq tinha que recarregar a aplicação
