### ISSUE TITLE
Label tap focus issue

### ISSUE THREAD

**Issue by Diego-Franco** [Cnilton/react-native-floating-label-input#42]
If we have two input fields in the same screen, and we tap in the label the first is focused, but if we try to focus the second one tapping in the label, the second input field is not focused immediately

it could be possible we need to do some logic in our side instead, but it was weird this is not happening if we click in the container (input box) 

using the sample from the ReadMe

```
<FloatingLabelInput
	label="Login"
	value={appleValue}
	onChangeText={value => setAppleValue(value)} />
<FloatingLabelInput
	label="Login"
	value={appleValue}
	onChangeText={value => setAppleValue(value)} />
```

https://user-images.githubusercontent.com/5623933/103596672-4f364000-4eb3-11eb-8431-a704aa3d7d5f.mov

**Comment by Cnilton** [comment]
Hi @Diego-Franco, maybe it's a bug reproducible only in the simulator? I couldn't reproduce it even on my simulator using your exact case. Can you confirm if this issue is happening on a real device?

**Comment by Diego-Franco** [comment]
it is happening in a real device, I tried on android and on iOS, this happens when you click in the label not in the container

**Comment by Cnilton** [comment]
I couldn't reproduce it with the provides code.. can you please provide the exact case you saw this bug?

**Comment by Diego-Franco** [comment]
Here is the video, I'm using the same code as I posted before, I just enable the touches in the video to show when I click in the label

https://user-images.githubusercontent.com/5623933/104229059-92873600-5400-11eb-953e-af172044417d.mov

**Comment by Cnilton** [comment]
Sorry @Diego-Franco, past weekend I couldn't test this. Soon I'll look into it.

**Comment by nipek** [comment]
I am having this issue where input won't focus when text input has value set by default @Cnilton , 

[https://drive.google.com/file/d/1t6_tBwG3Two8Led-wB6d6YUuyv38KBE3/view?usp=sharing](url)

**Comment by Cnilton** [comment]
Hi @nipek, sorry but I couldn't reproduce your error. Can you post the code for reproduction?

Also, @Diego-Franco, I still can't reproduce this.. couldn't it be some error on your onFocus or onBlur functions?

**Comment by Cnilton** [comment]
> Hi @nipek, sorry but I couldn't reproduce your error. Can you post the code for reproduction?
> 
> Also, @Diego-Franco, I still can't reproduce this.. couldn't it be some error on your onFocus or onBlur functions?

@nipek, @Diego-Franco, can you please provide a response?

**Comment by Diego-Franco** [comment]
I'm able to reproduce with no problem, either if I don't have onFocus or onBlur the issue still there, this only happens when you click the label, not the input area, so not sure if you can validate again

**Comment by Cnilton** [comment]
Still can't reproduce here on my side.. see video please:

https://i.imgur.com/vxxP2gb.gifv

**Comment by Diego-Franco** [comment]
> Still can't reproduce here on my side.. see video please:
> 
> https://i.imgur.com/vxxP2gb.gifv

wonder if could be only iOS related issue 🤔 do you have a way to validate that?

**Comment by Cnilton** [comment]
No, I don't 😓. I can't test iOS, because I don't own a Macbook.. Does this issue occur in android? Because previously you said you tested on both iOS and Android and I understood this issue was occurring on both.

**Comment by Diego-Franco** [comment]
I tested on a real device on Android and was happening, I didn't change any code, not sure if you would see something diff between simulator and real device

**Comment by Cnilton** [comment]
Tested on my Android, clicking on label, still can't reproduce:

```javascript
<View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <FloatingLabelInput label="Some label" value={val} onChangeText={(value)=>setVal(value)} />
      <FloatingLabelInput label="Some label" value={val2} onChangeText={(value)=>setVal2(value)} />
      <StatusBar style="auto" />
    </View>
```

<img src="https://i.imgur.com/NmNt5KA.gif" width="40%"/>

**Comment by Diego-Franco** [comment]
So weird, but I can say is happening on iOS, I don't see anything wrong with the code, can we leave this open until we can get more help. I tried to fix it, but is not working :(

**Comment by Cnilton** [comment]
Yeah, very weird.. okay, I'll leave this open while we can't get a hold of why is this happening. But one question: were you able to reproduce with my example?

**Comment by Diego-Franco** [comment]
Yes, using your code, and clicking in `Some label` I'm able to reproduce, when I click on Some label the first one lost the focus but the second one does nothing, just hide/close the keyboard

**Comment by Cnilton** [comment]
I see.. what version of Android are you using? My test case with a real device was using Android 11, and the test case with the simulator was using Android 10.

**Comment by Diego-Franco** [comment]
Same for me, Android 11 in my Pixel 4XL and yes I'm using the last update for the library, in iOS the version is 12.4.

**Comment by Cnilton** [comment]
Hi @Diego-Franco, can you still reproduce this issue on version 1.3.5?

**Comment by Cnilton** [comment]
@Diego-Franco, can you reproduce this issue on the latest version (1.3.7)?

**Comment by Cnilton** [comment]
Closing this due to no response and no reproducibility by me.
