### ISSUE TITLE
How to add touchableopacity inside FloatingLabelInput?

### ISSUE THREAD

**Issue by tcagkansokmen** [Cnilton/react-native-floating-label-input#45]
I want to Add "X" button inside input, but It doesnt allow it.
How can this be possible?

How can I add it inside?
Left component ok, but I need right component for that.

**Comment by Cnilton** [comment]
Hi @tcagkansokmen, I could add a *rightComponent* prop for that purpose. But now I have a doubt: how would it be if you were using a password-like input? I think this *rightComponent* should be "before" the show/hide component, right?

**Comment by tcagkansokmen** [comment]
Yeah It could be, but I guess, we don't use rightcomponent with "show/hide component" at the same time. But I guess yeah, It must be before that.

**Comment by Cnilton** [comment]
I agree. In this weekend I'll be checking all issues and pull requests and I'll add this prop.

**Comment by Cnilton** [comment]
Hi @tcagkansokmen, can you please check the new version 1.3.2 with this new prop?
