### ISSUE TITLE
`fontSize` and `fontColor` not being recognized in `labelStyles` and `inputStyles` props

### ISSUE THREAD

**Issue by free4mOriginal** [Cnilton/react-native-floating-label-input#47]
Before I start complaining, this is a great package that really filled a void for us.
However there are two seemingly minor but very problematic issues.

1) Problem with some styles in the `labelStyles` prop not being recognized:

Here's our component code :
```
      <FloatingLabelInput
        labelStyles={{
          fontFamily: loaded ? "poppins-medium" : null,
          fontSize: 16,
          color: "#BDBDBD",
        }}
        inputStyles={{
          fontFamily: loaded ? "poppins-medium" : null,
          fontSize: 16,
          color: "#666666",
        }}
        label={title}
        value={text}
        onChangeText={(value) => setText(value)}
      />
```

The fontFamily in the `labelStyles` prop is being read correctly, but the `fontSize` and `color` attributes are not reflected in the app, font color and size remain at default values - 14px and dark grayish blue. At the same time both font size and color from the `inputStyles` are correctly reflected in the user input text.

2) When setting the same styles to `globalStyles.js` they are not being read at all, and the color of the user input defaults to the focused label color for some reason. The `containerStyles` are read globally and locally just fine.

Please advise! Thanks in advance

**Comment by Diego-Franco** [comment]
for the label style you have the CustomLabelStyle props, where you can pass the colorBlurred and colorFocused, 

for the input, you can pass the prop as you're doing it now

**Comment by free4mOriginal** [comment]
Thank you!
The `colorBlurred` and `fontSizeBlurred` worked.

**Comment by Diego-Franco** [comment]
no problem, if that help you and solved your issue, feel free to close this
