### ISSUE TITLE
Label behavior issue with text

### ISSUE THREAD

**Issue by antoinebrtd** [Cnilton/react-native-floating-label-input#50]
Hello @Cnilton,

I'm using the latest version and I have issues with the label overlapping on the text both on ios and android (see videos), especially on ios where the label goes below and then on top of the text. Wouldn't it be preferable to remove the animation when the text input is filled?

Also label is focused when the text is empty (see picture).

Thanks

![142293570_1488179231387871_6536176645881936061_n](https://user-images.githubusercontent.com/34452191/105642961-fecf5400-5e5a-11eb-962c-fcf67af50a8d.jpg)

https://user-images.githubusercontent.com/34452191/105642954-e8c19380-5e5a-11eb-98b7-b6f03f128e03.mp4

https://user-images.githubusercontent.com/34452191/105642955-e8c19380-5e5a-11eb-98be-dd7379a39ae6.mp4

**Comment by Cnilton** [comment]
Hi @antoinebrtd, today while testing I could reproduce this, and I think I know why it is behaving like that. I'll work on it ASAP.

**Comment by Cnilton** [comment]
Hi @antoinebrtd, can you please test the new version?

**Comment by antoinebrtd** [comment]
Hi @Cnilton, tested on v1.3.4 and the issue still persists. Label still moves on mounted when there is some text, and label is focused on mounted when the text is empty

**Comment by Cnilton** [comment]
@antoinebrtd, I didn't understand what you mean about the issue. If you mean that the label appears overlapped with the value (when input starts with an initial value), there is a solution to this in the README.md, just using backgroundColor in labelStyles. The issue I said I found was that the label was translating down and then up when the input has an initial value.

**Comment by Cnilton** [comment]
@antoinebrtd can you please post some explanation?

**Comment by antoinebrtd** [comment]
@Cnilton the label is focused even with no text (see the picture I attached to this post). Other issues on IOS seem fixed, thank you

**Comment by antoinebrtd** [comment]
See attached video for more explanation

https://user-images.githubusercontent.com/34452191/106523735-8e09e680-64af-11eb-9e5f-55cfb7e78c37.mp4

**Comment by Cnilton** [comment]
I see, are you overriding the onBlur/onFocus methods? Can you please show the code for reproducibility?

**Comment by antoinebrtd** [comment]
I am not. I think the issue lies in the fact that the initial `value` prop is `null`. Works fine with an empty string, I'll change on my side. You can close the issue :)

**Comment by Cnilton** [comment]
Ok, yes that was the issue, after all this lib is based on a TextInput, and initial value should always be a string. Thanks!
