### ISSUE TITLE
How to remove border and keep only underline bottom border

### ISSUE THREAD

**Issue by seyaobey** [Cnilton/react-native-floating-label-input#54]
Hi. I've just discovered your component. On your home page you are displaying simple usages of this component.
I'm trying to get `this` look (just the underline bottom border):

![image](https://user-images.githubusercontent.com/2738569/106738746-9d587380-6618-11eb-99bf-4bc4185d76ce.png)

The default look of the component is the full border. Is there a flag I should toggle or should I apply some styling? It is not clear from the documentation.

Thanks for your assistance

**Comment by Cnilton** [comment]
Hi @seyaobey, I see that removing default styling isn't very clear at first. I shall create a *noDefaultStyle* prop for this. But currently the way to make it work is to you just declare the styles that you want to override, for example the containerStyle, if you use this prop, the borders will go away.

**Comment by seyaobey** [comment]
@Cnilton thansk for your reply. Just to let you know I tried to apply a custom style to `containerStyles` to keep only the bottom border. And I've observed 2 thinks (maybe I'm not good at styling...):

1. The border color seems to have changed
2. The floating label position messes up with the input text.

This is my custom style:
```
<FloatingLabelInput
      label="User name"
      value={text}
      onChangeText={setText}
      containerStyles={{
           borderWidth: 0,
           borderBottomWidth: 2,
      }} />
```

And here is screen of what I'm seeing (2 components with custom style and default styling)

![image](https://user-images.githubusercontent.com/2738569/106763032-b5d78680-6636-11eb-92ff-01bdf47f1fb2.png)

**Comment by Cnilton** [comment]
So, when you use the containerStyles, the way it works is that the prop is overridden, so all default styles from containerStyles will not take effect, so that's why the border color changes and the container height changes too. So you have to add in containerStyles those styles. Example: ```containerStyles={{borderColor="#123", height=50}}```

**Comment by Cnilton** [comment]
I'm going to close this, but feel free to open another issue for questions. Thanks!
