### ISSUE TITLE
while navigating with data and setting value as params data animation is not working

### ISSUE THREAD

**Issue by AasimuddinM** [Cnilton/react-native-floating-label-input#55]
i navigation to screen with data and and setting this params data as value prop to floating input but majorly label is not animating to upside sometimes its working 
![File](https://user-images.githubusercontent.com/70324804/106747859-71ee7c80-664a-11eb-89c5-a55fe11581f5.jpg)

**Comment by Cnilton** [comment]
Hi @AasimuddinM, are you using the onFocus/onBlur props, or are you setting the initial value of the input as null? Can you please provide the code you used for me to try to reproduce it?

**Comment by Cnilton** [comment]
@AasimuddinM can you please answer my previous questions?

**Comment by Cnilton** [comment]
Closing this issue due to no response.
