### ISSUE TITLE
while using onBlur and onFocus events it blocks the label animation

### ISSUE THREAD

**Issue by Uzef1997** [Cnilton/react-native-floating-label-input#56]
https://user-images.githubusercontent.com/45681786/108326762-a50b4100-71f0-11eb-818f-851432008dd9.mov

_Originally posted by @Uzef1997 in https://github.com/Cnilton/react-native-floating-label-input/issues/25#issuecomment-781146031_

**Comment by Cnilton** [comment]
Hi @Uzef1997, are you using the the isFocused prop as well? Can you please show your code for reproducibility?

**Comment by Cnilton** [comment]
@Uzef1997 can you please answer my previous questions?

**Comment by Cnilton** [comment]
Closing this due to no answer.

**Comment by coucoseth** [comment]
incase you have this issue, add this prop `isFocused={false}`
