### ISSUE TITLE
Vertically aligning text in multirow field

### ISSUE THREAD

**Issue by Leijoma** [Cnilton/react-native-floating-label-input#57]
Hi
Maybe it's just me not understanding how to do it, but i can not make the text in a multiline input field align top. It is always centered vertically. How can i adjust this?

**Comment by Cnilton** [comment]
Hi @Leijoma, I didn't quite understand your question. The default behavior when setting multiline to the floating-label-input is what you described, see the following code and image:

```javascript
<FloatingLabelInput multiline label="Some label" value={val} onChangeText={(value)=>setVal(value)} />
```

<img src="https://i.imgur.com/iEunDCl.png" width="40%"/>

**Comment by Leijoma** [comment]
Thanks for the quick response! I will go back to the drawing board and try to figure out what i'm doing wrong...

**Comment by Leijoma** [comment]
OK, It happens when i try to set the height of the inputfield by setting a height value in containerStyle. How do you set the height of the inputfield in your example above?

**Comment by Cnilton** [comment]
I didn't set any height to the input. When I skip a line it increases the height automatically. What you can do is set maxHeight.

**Comment by Leijoma** [comment]
OK, but is it possible to assign it a min height as well?

**Comment by Cnilton** [comment]
Just use something like: inputStyles={{minHeight:80}}

**Comment by Leijoma** [comment]
Thank you so much! Working now.
