### ISSUE TITLE
Upgrade reanimated to version 2

### ISSUE THREAD

**Issue by Ubax** [Cnilton/react-native-floating-label-input#59]
I propose reanimated upgrade to version 2. To do that all usages of `Easing` have to be changed into `EasingNode`. To keep compatibility I would propose to publish 
- library for reanimated 2 as 2.x.x
- library for reanimated 1 as 1.x.x.

This way it would be possible to use it with both versions. 

Additionally I think it would be a good idea to clean the released files - delete:
- eslint config
- prettier
- watchman
- app.json
- jest
- babel
- metro

from the released package.

**Comment by Ubax** [comment]
I created a PR for that #58.

**Comment by Cnilton** [comment]
Hi @Ubax, thanks for your contribution. I'll test it out and then release a new version.

**Comment by Cnilton** [comment]
Hi @Ubax, please try version 1.3.5 following the guide within the README.md.

**Comment by Ubax** [comment]
HI @Cnilton
It works in our project.
Thanks
