### ISSUE TITLE
conflicts with react-native-reanimated

### ISSUE THREAD

**Issue by coucoseth** [Cnilton/react-native-floating-label-input#60]
Animated node with ID 2 already exists, thats the error i get whenever i try to use this package in my react native project already having the react-native-reanimated package. something about two instances of reanimated

**Comment by Cnilton** [comment]
Hi @coucoseth, are you using this lib at version 1.3.5? If so, if in your project you are using react-native-reanimated v1, it will happen, unfortunately... For resolving this issue, you should or install react-native-floating-label-input@1.3.4, or install and use react-native-reanimated v2. The guideline for installing react-native-reanimated v2 is within the README.md.

**Comment by coucoseth** [comment]
i am running react-native-floating-label-input@1.3.4 and react-native-reanimated v2 and still getting the same error

**Comment by Cnilton** [comment]
But that's what is going wrong, as you see in the README.md, if you have this lib at version 1.3.4 you should have react-native-reanimated@1.13.2. Could you please try installing this version of reanimated?

**Comment by Cnilton** [comment]
@coucoseth, can you please provide an answer?

**Comment by coucoseth** [comment]
your solution works, thank you
