### ISSUE TITLE
TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

### ISSUE THREAD

**Issue by tborowy** [Cnilton/react-native-floating-label-input#61]
If I try use that library i have error and my whole app not work.
 `TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')`

I trying v 1.3.5 with reanimated v2 and old 1.3.4 with reanimated v1

**Comment by Cnilton** [comment]
Hi @tborowy, if you want to use version 1.3.5, you have to use reanimated v2. For using the reanimated v2 you have to follow the extra steps for reanimated v2 installation, which are within the README.md. As I stated in the README.md if you have some trouble building your app, try removing node_modules folder, and running yarn or npm install.
