### ISSUE TITLE
 No podspec file was found.

### ISSUE THREAD

**Issue by vandiepbui** [Cnilton/react-native-floating-label-input#62]
I install version ^4.2.0 and when pod install, I receive this message.
use_native_modules! skipped the react-native dependency 'react-native-floating-label-input'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven
    podspec. See https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec

**Comment by Cnilton** [comment]
Hi @vandiepbui, I didn't understand... there is no 4.2.0 version of this lib. Can you please explain again?

**Comment by Cnilton** [comment]
Closing this due to no answer.

**Comment by donjerick** [comment]
Hi @Cnilton, I'm also facing this issue when running `pod install` after installing via `yarn add react-native-floating-label-input`

Complete message:
`[!] use_native_modules! skipped the react-native dependency 'react-native-floating-label-input'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary
    podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The
    react-native-webview podspec is a good example of a package.json driven
    podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it
    manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library`

This causes react-native-floating-label-input package not included in Pods for iOS.

Using the following versions:
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-floating-label-input": "1.3.7",
"react-native-reanimated": "^2.1.0",

**Comment by donjerick** [comment]
It does not throw error on build but the app crashes on the screen that has FloatingLabelInput element.

**Comment by Cnilton** [comment]
I see... can you please try following these steps for stopping this issue from happening to your app:

[https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library](url)

Unfortunately, I can't test this on iOS, but I'll try to fix this.

**Comment by donjerick** [comment]
Disabling autolink for ios will just skip checking for podspec but still does not install the library in /ios/Pods thus the library will still not work on an ios app (UI freezes when the screen rendering FloatingLabelInput element/s gets called in the foreground).

This might help on the issue for podspec generation: https://github.com/brodybits/create-react-native-module

**Comment by Cnilton** [comment]
Can you please test version 1.3.8?

**Comment by donjerick** [comment]
Got an error:
> [!] The `react-native-floating-label-input` pod failed to validate due to 1 error:
>     - ERROR | attributes: Missing required attribute `authors`.
>     - WARN  | attributes: Missing required attribute `license`.
>     - WARN  | license: Missing license type.

Maybe forgot to update `package.json`?

**Comment by Cnilton** [comment]
Yes, I've updated it now. Can you please test version 1.3.9?

**Comment by donjerick** [comment]
Works well now at version 1.3.9. Thank you @Cnilton! 🚀
