### ISSUE TITLE
Placeholder placement in multiline input get centered

### ISSUE THREAD

**Issue by Leijoma** [Cnilton/react-native-floating-label-input#65]
When having a multi line input field with a height setting to more than one row, the placeholder text is vertically centered. It needs to be aligned top to look good. 
![simulator_screenshot_B9EDC6F8-08AD-476E-9540-23E1231552F0](https://user-images.githubusercontent.com/59127833/113573214-f7c28000-9619-11eb-90b5-ae4db3d23f5a.png)

**Comment by Cnilton** [comment]
Hi @Leijoma, you can override this by using ***customLabelStyles*** prop and setting the distance from the top you want the label to be when blurred and when focused.

**Comment by Leijoma** [comment]
That's great, but what property do i use to achieve that?

**Comment by Leijoma** [comment]
Got it! 
  customLabelStyles={{ topBlurred: -25}}
