### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNativeReanimated.EasingNode.linear'

### ISSUE THREAD

**Issue by Bogzzz** [Cnilton/react-native-floating-label-input#67]
Hello, I am trying to use this library but it keeps crashing and giving an error
---TypeError: undefined is not an object (evaluating '_reactNativeReanimated.EasingNode.linear')
Saying the issues is in \node_modules\react-native-floating-label-input\src\index.tsx with code line 439
and node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js line 15561.
Can any one help me out

**Comment by Cnilton** [comment]
Hi @Bogzzz, did you follow the instructions in the README.md? If you are using this lib at version 1.3.5 or higher you have to install react-native-reanimated v2.

**Comment by Bogzzz** [comment]
yea im having difficulty installing V2 . im using Expo and every time i follow their steps. it installs 1.3.... something

**Comment by Bogzzz** [comment]
I fixed it. Thank you

**Comment by Cnilton** [comment]
Can you please comment on what was the issue?

**Comment by Bogzzz** [comment]
The first issue was that my Expo was older release then what the ReanimatedV2 is asking for. So I had to reinstall Expo-CLI from scratch. Then I ran a npm install react-native-reanimated@2. Deleted Node Modules and ran npm install . And it seems to be working right now :)

**Comment by Bogzzz** [comment]
Great job on the Library. ReanimatedV2 and Expo didnt do a good job on merging them together so far xD

**Comment by Cnilton** [comment]
Thanks! Thanks for your contribution as well, I'll be closing this issue then. Feel free to open an issue if you encounter any other bugs or have any other doubts.
