### ISSUE TITLE
Android and iOS device border textfiled need to lable and textinput center align

### ISSUE THREAD

**Issue by harshal311989** [Cnilton/react-native-floating-label-input#68]
Hello team, I am using this plugon in my project and i used rounded border textfield in my whole app. My actual UI is as below 
![Screenshot 2021-04-29 at 12 04 14 PM](https://user-images.githubusercontent.com/75067288/116510788-19deb380-a8e3-11eb-8e66-ae410283c683.png)

But currently in my application i got below textfiled with bottom gap 
![AA](https://user-images.githubusercontent.com/75067288/116510836-2fec7400-a8e3-11eb-9ae7-f5cc509e2ba1.png)

Below is my code for my textfield 
<View style={{ marginTop: 10 }}>
               <FloatingLabelInput
                                label={"FirstName}
                                value={firstName}
                                onChangeText={(value) => {
                                    this.setFirstName(value)
                                }}
                                labelStyles={{
                                    fontFamily: globals.ProximaNovaRegular,
                                    color: 'black',
                                    marginLeft:(Platform.OS == 'ios') ? -5 : 0
                                }}
                            />
                        </View> 
For tectfield border i change style as below in plugin style.js
            container: {
    flexDirection: 'row',
    color: colors.darkWarmGrey,
    borderColor: colors.darkWarmGrey,
    borderWidth: 1,
    borderRadius: 30,
    paddingTop:(Platform.OS==='android') ? 0 : 5,
    paddingLeft:20,
    paddingRight:20,
    paddingBottom:(Platform.OS==='android') ? 0 : 5,
    marginTop:(Platform.OS==='android') ? 5 : 5,
    alignContent: 'center',
    justifyContent: 'center',
  },

Any idea how I can make center align both as i want in real desgin

**Comment by Cnilton** [comment]
Hi @harshal311989, I tested the code you provided, and unfortunately I couldn't reproduce this issue that the input value isn't centered. Are you sure all styles set to that input in the image are listed? Are you sure that all these conditional paddings are necessary? Maybe you can add specific height to the containerStyles.

**Comment by harshal311989** [comment]
@Cnilton In your plugin style.js I make change code as below 

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    color: colors.darkWarmGrey,
    borderColor: colors.darkWarmGrey,
    borderWidth: 1,
    borderRadius: 30,
    paddingTop:(Platform.OS==='android') ? 0 : 5,
    paddingLeft:20,
    paddingRight:20,
    paddingBottom:(Platform.OS==='android') ? 0 : 5,
    marginTop:(Platform.OS==='android') ? 5 : 5,
    alignContent: 'center',
    justifyContent: 'center',
  },
  input: {
    minHeight: 28,
    color: '#000',
    paddingVertical: 5,
    flex: 1,
    zIndex: 10,
  },
  img: {
    height: 25,
    width: 25,
    alignSelf: 'center',
  },
  toggleButton: {
    zIndex: 11,
    alignSelf: 'center',
    justifyContent: 'flex-end',
  },
  countdown: {
    position: 'absolute',
    right: 11,
    bottom: 0,
    color: colors.darkWarmGrey,
    fontSize: 10,
  },
});
I did not give specific height on that

**Comment by Cnilton** [comment]
So @harshal311989, testing with the provided styles:

```
<FloatingLabelInput
        label={'Label'}
        value={flateName}
        onChangeText={value => {
          setFlateName(value);
        }}
        hintTextColor={'#aaa'}
        hint="55 (22) 98765-4321"
        inputStyles={{
          minHeight: 28,
          color: '#000',
          paddingVertical: 5,
          flex: 1,
          zIndex: 10,
        }}
        containerStyles={{
          flexDirection: 'row',
          borderWidth: 1,
          borderRadius: 30,
          paddingTop: Platform.OS === 'android' ? 0 : 5,
          paddingLeft: 20,
          paddingRight: 20,
          paddingBottom: Platform.OS === 'android' ? 0 : 5,
          marginTop: Platform.OS === 'android' ? 5 : 5,
          alignContent: 'center',
          justifyContent: 'center',
        }}
      />
```

output the following:

![untitled (1)](https://user-images.githubusercontent.com/40298250/117217446-c3d4a900-add7-11eb-928e-74d47aeb1f6b.gif)

**Comment by Cnilton** [comment]
@harshal311989, any updates?

**Comment by harshal311989** [comment]
@Cnilton  Sorry for late reply I chekced code and I also check my style and I use your latest version plugin and modify styles it is working now . Thanks for your support
