### ISSUE TITLE
CSS Label  color doesnt work

### ISSUE THREAD

**Issue by Bogzzz** [Cnilton/react-native-floating-label-input#69]
Hello, Im having an issue with changing label color from blue to anything else ,as well as font size.
```
---RegisterStyle.js
  label: {
    backgroundColor: '#fff',
    paddingHorizontal: 5,
    marginLeft: 13,
    fontSize: 25,
    color: 'red',
  },
---Register.js
 labelStyles={RegisterStyles.label}
```
[What i get](https://imgur.com/DgMZdrT)

**Comment by Cnilton** [comment]
Hi @Bogzzz, which version are you using? Also, did you try using the **customLabelStyles** prop?

**Comment by Bogzzz** [comment]
using V1.3.7. and CustomLabelStyles prop is used for on Focus.

**Comment by Bogzzz** [comment]
But I need it not on Focus

**Comment by Cnilton** [comment]
So @Bogzzz, actually you need to use:

```
customLabelStyles={{
          colorBlurred: 'red',
          colorFocused: 'yellow',
}}
```

This lib handles focus by itself if you do not use the **onFocus**, **onBlur**, and **isFocused** props.

Try that piece of code with the color you want. If you want the same color whether it is focused or not, just pass the same color..

**Comment by Bogzzz** [comment]
Thank you , it worked :)

**Comment by Cnilton** [comment]
You're welcome! Feel free to open another issue if you need to!
