### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by sritharIOS** [Cnilton/react-native-floating-label-input#71]
Hi,

 How to use here for email validation and entry?

**Comment by Cnilton** [comment]
Hi, this lib does not have an e-mail validation on its own, but you can implement it by yourself with the onChangeText prop. Do you need help setting it up?

**Comment by sritharIOS** [comment]
Thank you @Cnilton  for your reply. I will try on my end and If not works, I need your help.

**Comment by Cnilton** [comment]
@sritharIOS, any updates? Can we close this issue?

**Comment by sritharIOS** [comment]
@Cnilton Fixed the issue:  const validate = text => {
    console.log(text);
    let reg = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w\w+)+$/;
    if (reg.test(text) === false) {
      console.log('Email is Not Correct');
      return true;
    } else {
      console.log('Email is Correct');
      return false;
    }
  };
