### ISSUE TITLE
Custom Label animation speed

### ISSUE THREAD

**Issue by sritharIOS** [Cnilton/react-native-floating-label-input#72]
Hi Author,

I would like to control the custom label animation speed. It looks slow. Please guide me on how to increase the speed of that one.

**Comment by sritharIOS** [comment]
I got  animationDuration property to achieve that. thanks.

**Comment by coucoseth** [comment]
kindly document this, also real quick, how can i use this prop?

**Comment by Cnilton** [comment]
Hi @coucoseth, animationDuration is set by miliseconds:
```javascript
animationDuration={100}
```
