### ISSUE TITLE
While using onBlur and onFocus the label animation works only after i start typing

### ISSUE THREAD

**Issue by coucoseth** [Cnilton/react-native-floating-label-input#74]
I included `isFocused={false}` and the label does not animate when focused, only when i start typing, help please? desired output is animation of label on focus

**Comment by Cnilton** [comment]
Hi @coucoseth, as stated in the README.md, if you use the **isFocused** prop, you will have to handle the **onFocus** and **onBlur** props as well. Try using the isFocused with a state variable, like:

```javascript
const [val, setVal] = useState('');
const [isFocused, setIsFocused] = useState(false);
// ...
<FloatingLabelInput
    value={val}
    onChangeText={(newVal)=> setVal(val)}
    isFocused={isFocused}
    onFocus={()=> setIsFocused(true)}
    onBlur={()=> setIsFocused(false)}
/>
```

**Comment by coucoseth** [comment]
instead of `isFocused={false}` i solved this by using a state variable `isFocused={isfieldFocused}` then in `onBlur` i set `isfieldFocused` to false and `onFocus` i set it to true
