### ISSUE TITLE
Bug with label focusing

### ISSUE THREAD

**Issue by lazarspasic96** [Cnilton/react-native-floating-label-input#78]
<img width="128" alt="Capture" src="https://user-images.githubusercontent.com/44000018/118281580-aa191d00-b4cd-11eb-8553-fc00eba1d9c7.PNG">

When I run the application in development mode it works totally fine, but when I build a release app the label not work. It's the same with custom label styles and without. I deliver the default name value to the floating input. It's not an empty string when the component is mounted.

```
      <FloatingLabelInput
        label={label}
        value={value}
        onChangeText={onChange}
        keyboardType={keyboardType}
        autoCapitalize={autoCapitalize}
        isPassword={isPassword}
        customShowPasswordComponent={customShowPasswordComponent}
        customHidePasswordComponent={customHidePasswordComponent}
        isFocused={isFocused}
        onFocus={() => { setIsFocused(true) }}
        onBlur={() => { setIsFocused(false) }}
        ref={inputRef}
        blurOnSubmit={false}
        {...rest}
```
        
        This is my code.

**Comment by Cnilton** [comment]
Hi, @lazarspasic96 can you please post those variables because without them I cannot reproduce the same environment of the issue described. Also, what is defined in the `...rest` prop?

**Comment by lazarspasic96** [comment]
`const FormInput = ({ field, label, value, onChange, keyboardType, autoCapitalize, isPassword,
                     customShowPasswordComponent, customHidePasswordComponent, errors, inputRef, ...rest }) => {

  const [isFocused, setIsFocused] = useState(false)`
  
  This is what my FormInput component receives as props. The res props is just for sending some additional props to the Floating label"

  const [firstName, setFirstName] = useState(name)
  const [lastName, setLastName] = useState(surname)

This is where I call that component
           <FormInput label="Ime"
              errors={errorMessages}
              field="name"
              value={firstName}
              inputRef={firstNameRef}
              onSubmit={() => firstNameRef.current.focus()}
              returnKeyType="next"
              maxLength={50}
              onChange={setFirstName}
              containerStyles={formStyles.FormInput} />
              
              The values for name and surname I set I the useEffect
                useEffect(() => {
    setFirstName(name)
    setLastName(surname)
  }, [dateOfBirth, userGender, name, surname])
  
  All work perfectly fine in development mode, but when I build app, it does not work very well.

**Comment by Cnilton** [comment]
Okay, I'll try to reproduce this issue. Can you inform the used version of this lib?

**Comment by lazarspasic96** [comment]
Current version is 1.3.4

**Comment by lazarspasic96** [comment]
Any update on this? @Cnilton

**Comment by lazarspasic96** [comment]
@Cnilton Okay, thank you :)

**Comment by Cnilton** [comment]
@lazarspasic96, I'm sorry, but I couldn't reproduce this issue. Code used:

```javascript
<FloatingLabelInput
      label={'label'}
      value={val}
      onChangeText={(newValue)=> setVal(newValue)}
      autoCapitalize={'words'}
      isFocused={focused}
      onFocus={() => { setFocused(true) }}
      onBlur={() => { setFocused(false) }}
      blurOnSubmit={false}
      />
```

and running with ```npx react-native run-android --variant=release```

for disabling animation use ```staticLabel``` prop.

**Comment by Cnilton** [comment]
@lazarspasic96 any updates?

**Comment by lazarspasic96** [comment]
@Cnilton I have not fixed it. Still didn't work in a release. You can close the issue, and I will reach out to you if I find out what the issue is.

**Comment by Cnilton** [comment]
@lazarspasic96, ok I'll do so. Did you try running with ```npx react-native run-android --variant=release``` ?
