### ISSUE TITLE
autoFocus prop

### ISSUE THREAD

**Issue by sritharIOS** [Cnilton/react-native-floating-label-input#80]
I want to use the autoFocus property and set a default value when the page renders. How to achieve this one?

**Comment by Cnilton** [comment]
Hi @sritharIOS, I believe you can use the autoFocus as you want because this component extends Textinput props. To set a default value when the page renders, just initialize the state value used on the input with the value you want.

**Comment by sritharIOS** [comment]
<img width="300" alt="Screen Shot 2021-05-17 at 4 15 39 PM" src="https://user-images.githubusercontent.com/16605998/118563062-20668b00-b72b-11eb-92e2-c6ac3b1da828.png">

I tried to set the state but custom label animation is not working. Please refer to the attached screen.

**Comment by sritharIOS** [comment]
![Uploading Screen Shot 2021-05-17 at 4.17.54 PM.png…]()

**Comment by sritharIOS** [comment]
<img width="502" alt="Screen Shot 2021-05-17 at 4 18 45 PM" src="https://user-images.githubusercontent.com/16605998/118563305-8fdc7a80-b72b-11eb-89d4-a0bfd4c66897.png">

**Comment by sritharIOS** [comment]
@Cnilton  This issue has been resolved while setting the value during the state initialization. Thanks for the idea.
  const [text, setText] = useState(defaultValue);
