### ISSUE TITLE
autoCapitalize doesnt work

### ISSUE THREAD

**Issue by fadiaIW** [Cnilton/react-native-floating-label-input#83]
Hey, 
autoCapitalize does'nt seem to work. I'm using it like this : 

<  FloatingLabelInput
                    label={'Email Address*'}
                    value={username}
                    onChangeText={(value) => setUsername(value)}
                    containerStyles={{ borderBottomWidth: 2, borderBottomColor: COLORS.primaryColor, paddingBottom: 10, paddingTop: 35 }}
                    customLabelStyles={{ fontSizeFocused: 12, fontSizeBlurred: 12, colorFocused: COLORS.secondaryColor, colorBlurred: COLORS.secondaryColor, paddingBottom: 20, }}
                    inputStyles={styles.inputStyle}
                    ref={ref => { usernameRef.current = ref }}
                    **autoCapitalize='none'**
                    autoCorrect={false}
                    
               />

This has no effect and the first letter is always capital by default.

**Comment by Cnilton** [comment]
Hi @fadiaIW, I see you closed this issue, were you able to workaround the issue?

**Comment by fadiaIW** [comment]
> Hi @fadiaIW, I see you closed this issue, were you able to workaround the issue?

Hey, yes, I restarted my Metro and the same code worked perfectly fine! Thanks!
