### ISSUE TITLE
Click cross icon textfiled Placeholder not set initial postion

### ISSUE THREAD

**Issue by harshal311989** [Cnilton/react-native-floating-label-input#84]
Hi @Cnilton I am using your component in my app and I face one issue like I have one textfield and right side cross icon for clear text so when i click on cross icon text is clearing but place holder not set as initial postion by animation see my aatchment 

https://user-images.githubusercontent.com/75067288/122557739-cffc8900-d05a-11eb-965b-cd9b3bed6e95.mov

Below is my code 

<FloatingLabelInput
                 label={textTranslation.myPets.STARTTYPE}
                value={searchAllery}
              onChangeText={(value) => {
                  this.searchFilterFunction(value)
             }}
            labelStyles={{
                fontFamily: globals.ProximaNovaRegular,
                color: colors.darkWarmGrey,
                marginLeft:(Platform.OS == 'ios') ? -5 : 0
            }}
           rightComponent={
              <TouchableOpacity style={{ alignItems: 'center', justifyContent: 'center' }} onPress={() => { this.closeKeyBoard() }} >
                   <Image source={images.shippingAddress.cancel} style={styles.cancelIconModal} resizeMode={'contain'} />
             </TouchableOpacity>
             }
            ref="myInput"
            />

closeKeyBoard(){
        Keyboard.dismiss();
        this.refs.myInput.blur()
        this.setState({ searchAllery: '' })
    }

Let me know what i need to do on this?
I am using latest version 1.3.7 version of this plugin

**Comment by Cnilton** [comment]
Hi @harshal311989, I'm sorry but I couldn't reproduce your issue using the following code:

```javascript
import React, {Component} from 'react';

import {View, Text, TouchableOpacity, Keyboard} from 'react-native';

import {FloatingLabelInput} from 'react-native-floating-label-input';

class Test extends Component {
  state = {
    searchAllery: '',
  };

  closeKeyBoard() {
    Keyboard.dismiss();
    this.refs.myInput.blur();
    this.setState({searchAllery: ''});
  }

  render() {
    return (
      <FloatingLabelInput
        label={'STARTTYPE'}
        value={this.state.searchAllery}
        onChangeText={value => {
          this.setState({searchAllery: value});
        }}
        // labelStyles={{
        //     fontFamily: globals.ProximaNovaRegular,
        //     color: colors.darkWarmGrey,
        //     marginLeft: (Platform.OS == 'ios') ? -5 : 0
        // }}
        rightComponent={
          <TouchableOpacity
            style={{alignItems: 'center', justifyContent: 'center'}}
            onPress={() => {
              this.closeKeyBoard();
            }}>
            {/* <Image source={images.shippingAddress.cancel} style={styles.cancelIconModal} resizeMode={'contain'} /> */}
            <Text>Fechar</Text>
          </TouchableOpacity>
        }
        ref="myInput"
      />
    );
  }
}

export default Test;

```

<img src ="https://i.imgur.com/GYhtdAV.gif" width="40%"/>

**Comment by harshal311989** [comment]
@Cnilton  I checked your code for single textinput it is working due to in your code when you close keyboard textinput cursor is there but in my video when i click cross icon my textinput cursor focus is gone that is the problem placehodler not animated.

**Comment by harshal311989** [comment]
@Cnilton I resolved my bug with below code in my js file 

For iOS 
```
closeKeyBoard(){
        setTimeout(() => {
            this.setState({searchAllery: '', searchPreConditions: ''});
            this.refs.myInput.focus();
            setTimeout(() => {
                this.refs.myInput.blur();
            },  0);
        }, 0);
    }
```

For Android 
 ```
closeKeyBoardAndroid(){
        this.setState({searchAllery: '', searchPreConditions: ''});
            this.refs.myInput.focus();
            this.refs.myInput.blur();
    }
```

Because in android keyboard open issue is there so i remove timout from that now it is working and you can close this issue. Thanks for your time :)
