### ISSUE TITLE
Question: Can inputs be disabled

### ISSUE THREAD

**Issue by fakeheal** [Cnilton/react-native-floating-label-input#86]
Hey, 

can the input be disabled programatically? I tried passing `disabled={true}`, but I don't think it did anything. I couldn't find anything in the README, too.

**Comment by Cnilton** [comment]
Hi @fakeheal, I think you need both **disable** and **focusable** to achieve your goal. Can you please try it out?

**Comment by SaadBinWaheed-empglabs** [comment]
Disabled to be passed where?

**Comment by Cnilton** [comment]
@SaadBinWaheed-empglabs I'm sorry, there are no props like I said. The right property would be *editable* :

```javascript
...
<FloatingLabelInput
// ...
editable={false}

```
