### ISSUE TITLE
Padding between label and top border

### ISSUE THREAD

**Issue by teckbeng-payboy** [Cnilton/react-native-floating-label-input#87]
I would like to ask how can I add some padding to the top of container when the label is in focused. Currently the label is too near to the top border when is in focused and i would like to make it same space as the padding under the input.

Attached is the video for demo
https://user-images.githubusercontent.com/85466071/127465477-f1d0edc6-5931-4484-8651-09bf9ea998e8.mov

**Comment by Cnilton** [comment]
@teckbeng-payboy you could use **customLabelStyles** prop to customize, check the readme.md
