### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNativeReanimated.EasingNode.linear'

### ISSUE THREAD

**Issue by Dugnist** [Cnilton/react-native-floating-label-input#88]
![image](https://user-images.githubusercontent.com/6489460/127611843-c9a63a50-571c-478d-9dff-486a7618bcb7.png)
![image](https://user-images.githubusercontent.com/6489460/127611868-54b3e68d-6120-4f52-95c1-9e5c3d317b06.png)

**Comment by Dugnist** [comment]
![image](https://user-images.githubusercontent.com/6489460/127611938-7ea47fcf-e4cb-4484-ab6a-0394d6202e98.png)

**Comment by Dugnist** [comment]
I just install 1.13.2 and got the same error...

![image](https://user-images.githubusercontent.com/6489460/127612159-6aa62d7f-f0ec-4d22-ad48-3302af63dde2.png)

**Comment by Dugnist** [comment]
![image](https://user-images.githubusercontent.com/6489460/127612219-2086d9d3-02cb-4376-8cee-8dd3e05089ef.png)

**Comment by Cnilton** [comment]
Hi @Dugnist, I'm sorry for taking do long, this weekend I'll be checking this issue.

**Comment by Cnilton** [comment]
@Dugnist, I'm sorry, but in my end couldn't reproduce this issue:

![image](https://user-images.githubusercontent.com/40298250/129119118-09b6cb16-c9d5-430b-bbae-ba374e252ec3.png)
![image](https://user-images.githubusercontent.com/40298250/129119139-a3323173-b698-413e-8625-40f9f5e46fe1.png)
