### ISSUE TITLE
Error with RN 0.65

### ISSUE THREAD

**Issue by teckbeng-payboy** [Cnilton/react-native-floating-label-input#92]
![simulator_screenshot_D17009BF-CCD1-4147-88B7-8FF478E04533](https://user-images.githubusercontent.com/85466071/130384908-0bfaccc8-9ede-4d93-a2a1-757bcaf3f81f.png)

This only happen on RN0.65 when you click on the text input

**Comment by Cnilton** [comment]
Hi @teckbeng-payboy, I'll check this weekend!
